# Generated by Django 2.1.7 on 2019-02-27 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_solutions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Solutions',
            new_name='Solution',
        ),
    ]
