# Generated by Django 2.1.7 on 2019-03-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20190227_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='next_contact',
            field=models.DateField(blank=True, null=True),
        ),
    ]
